'use client';
import {useEffect,useState} from 'react';
import {ArrowRight,ArrowLeft,Shield,Sun,Sparkles,Layers,Truck,Wrench,Check,Clock,MapPin,Phone,ChevronRight} from 'lucide-react';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Checkbox} from '@/components/ui/checkbox';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {services,estimate,money,timings,modes} from '@/lib/catalog';
import {inServiceArea,serviceAreaLabel} from '@/lib/service-area';
const icons={shield:Shield,sun:Sun,sparkles:Sparkles,layers:Layers,truck:Truck,wrench:Wrench};
const tintFilms=[['dyed','Dyed'],['carbon','Carbon'],['ceramic','Ceramic']] as const;
const tintCoverage=[['front-two','Two front windows'],['sides-rear','All sides + rear'],['entire','Entire vehicle incl. windshield'],['windshield','Windshield only'],['roof','Sunroof / panoramic roof'],['specific','Specific windows']] as const;
export function Pick({label,value,onChange,options,labels}:{label:string,value:string,onChange:(v:string)=>void,options:readonly string[],labels?:readonly string[]}){return <label className="field"><span>{label}</span><Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label} className="picker"><SelectValue placeholder="Select"/></SelectTrigger><SelectContent>{options.map((v,i)=><SelectItem value={v} key={v}>{labels?.[i]??v}</SelectItem>)}</SelectContent></Select></label>}
export function Header(){return <header className="topbar"><a href="/" className="brand"><img className="brand-mark" src="/capital-auto-concierge-mark.png" alt=""/><span>CAPITAL<small>AUTO CONCIERGE</small></span></a><div className="toplinks"><span><MapPin size={15}/> WASHINGTON · MARYLAND · VIRGINIA</span><a href="/leads">Concierge desk <ChevronRight size={15}/></a></div></header>}
export default function Estimator(){
 const [step,setStep]=useState(0),[selected,setSelected]=useState<Record<string,string>>({}),[modal,setModal]=useState(false),[success,setSuccess]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[consent,setConsent]=useState(false);
 const [form,setForm]=useState({year:'',make:'',model:'',trim:'',zip:'',timing:'',deadline:'',mode:'Discuss with concierge',destination:'',transportMethod:'Discuss with concierge',condition:'',name:'',email:'',phone:'',contactTime:''});
 const [requestId,setRequestId]=useState(''),[turnstileToken,setTurnstileToken]=useState(''),[website,setWebsite]=useState('');
 const turnstileKey=process.env.NEXT_PUBLIC_TURNSTILE_SITE_KEY;useEffect(()=>{const bytes=crypto.getRandomValues(new Uint8Array(16));bytes[6]=(bytes[6]&15)|64;bytes[8]=(bytes[8]&63)|128;const hex=Array.from(bytes,b=>b.toString(16).padStart(2,'0')).join('');setRequestId([hex.slice(0,8),hex.slice(8,12),hex.slice(12,16),hex.slice(16,20),hex.slice(20)].join('-'));},[]);
 useEffect(()=>{if(!modal||!turnstileKey||success)return;const w=window as any;const render=()=>{const el=document.getElementById('cac-turnstile');if(!el||el.childElementCount)return;w.turnstile?.render(el,{sitekey:turnstileKey,callback:(t:string)=>setTurnstileToken(t),'expired-callback':()=>setTurnstileToken(''),'error-callback':()=>setTurnstileToken('')});};if(w.turnstile){render();return;}const s=document.createElement('script');s.src='https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit';s.async=true;s.onload=render;document.head.appendChild(s);},[modal,turnstileKey,success]);
 const [zipInfo,setZipInfo]=useState<{ok:boolean,place:string}|null>(null);
 useEffect(()=>{if(!/^\d{5}$/.test(form.zip)){setZipInfo(null);return;}const ok=inServiceArea(form.zip);setZipInfo({ok,place:''});const life=new AbortController();fetch('https://api.zippopotam.us/us/'+form.zip,{signal:life.signal}).then(r=>r.ok?r.json():null).then((d:any)=>{const pl=d?.places?.[0];if(pl)setZipInfo({ok,place:`${pl['place name']}, ${pl['state abbreviation']}`});}).catch(()=>{});return()=>life.abort();},[form.zip]);
 const change=(key:string,value:string)=>setForm(f=>({...f,[key]:value}));const e=estimate(selected);
 const title=['Your vehicle, first.','What can we take care of?','On your terms.'][step];
 const input=(key:keyof typeof form,label:string,type='text',required=false)=><label className="field"><span>{label}</span><input type={type} inputMode={key==='zip'?'numeric':undefined} pattern={key==='zip'?'[0-9]*':undefined} value={form[key]} onChange={ev=>change(key,key==='zip'?ev.target.value.replace(/\D/g,'').slice(0,5):ev.target.value)} required={required} maxLength={key==='zip'?5:100} min={type==='date'?new Date().toISOString().slice(0,10):undefined} placeholder={key==='model'?'e.g. 911 Targa 4S':key==='trim'?'Optional':key==='zip'?'e.g. 20854':undefined} aria-describedby={key==='zip'?'zip-hint':undefined}/>{key==='zip'&&<small id="zip-hint" className={'zip-hint '+(zipInfo?zipInfo.ok?'ok':'no':'')} style={{marginLeft:0}}>{zipInfo?<>{zipInfo.place&&zipInfo.place+' · '}{zipInfo.ok?'In our service area ✓':'Outside our current service area'}</>:'We serve '+serviceAreaLabel+'.'}</small>}</label>;
 function next(){setError('');if(step===0&&(!form.year||!form.make||!form.model.trim()||!/^\d{5}$/.test(form.zip))){setError('Please enter the year, make, model and five-digit ZIP code.');return;}if(step===0&&!inServiceArea(form.zip)){setError(`We currently serve ${serviceAreaLabel}. If you're just outside that area, contact us directly and we'll see what we can do.`);return;}if(step===1&&!Object.keys(selected).length){setError('Choose at least one service to continue.');return;}setStep(s=>s+1);}
 function discuss(){if(!form.timing){setError('Please choose your timeframe.');return;}if(form.timing==='By a specific date'&&(!form.deadline||form.deadline<new Date().toISOString().slice(0,10))){setError('Choose today or a future date.');return;}setError('');setModal(true);}
 async function submit(ev:React.FormEvent){ev.preventDefault();if(!consent){setError('Please agree to be contacted about this request.');return;}if(turnstileKey&&!turnstileToken){setError('Please complete the verification check.');return;}setBusy(true);setError('');try{const res=await fetch('/api/leads',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,selected,consent,requestId,turnstileToken,website})});const data=await res.json() as {error?:string,id:string};if(!res.ok)throw new Error(data.error);setSuccess(data.id);}catch(err){setError(err instanceof Error?err.message:'Unable to save. Please retry.');}finally{setBusy(false);}}
 useEffect(()=>{const ctx=(document as any).modelContext;if(!ctx?.registerTool)return;const life=new AbortController();Promise.resolve(ctx.registerTool({name:'read_vehicle_estimate',description:'Read current vehicle services and preliminary estimate. Does not submit a lead or book work.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:(args:any)=>{if(!args||Object.keys(args).length)throw new Error('No arguments expected');return {vehicle:[form.year,form.make,form.model].join(' '),...e,timing:form.timing,deadline:form.deadline,expediteFee:'Not included; manual confirmation required',finalQuote:'After inspection'};}},{signal:life.signal})).catch(()=>{});return()=>life.abort();},[form,e]);
 return <><Header/><main className="shell"><div className="intro"><div><p className="eyebrow">YOUR VEHICLE. OUR ATTENTION.</p><h1>Your car,<br/><em>in good hands.</em></h1></div><p>Protection, refinement and transport.<br/>Start with an estimate. We’ll take it from there.</p></div>
 <div className="workspace"><section className="configurator"><nav className="steps" aria-label="Estimate steps">{['Vehicle','Services','Preferences'].map((v,i)=><button key={v} disabled={i>step} onClick={()=>{setStep(i);setError('');}} className={i===step?'active':''} aria-current={i===step?'step':undefined}><span>{i<step?<Check size={14}/>:String(i+1).padStart(2,'0')}</span>{v}</button>)}</nav>
 <div className="step-content"><p className="eyebrow">STEP {String(step+1).padStart(2,'0')} / 03</p><h2>{title}</h2><p className="muted">{['Tell us what you drive. No contact details needed yet.','Choose one service or build your own combination.','Tell us where, when, and anything we should know.'][step]}</p>
 {step===0&&<><div className="fields"><Pick label="Year" value={form.year} onChange={v=>change('year',v)} options={Array.from({length:78},(_,i)=>String(2027-i))}/><Pick label="Make" value={form.make} onChange={v=>change('make',v)} options={['Porsche','BMW','Mercedes-Benz','Audi','Range Rover','Ferrari','Lamborghini','McLaren','Aston Martin','Bentley','Rolls-Royce','Lexus','Tesla','Lucid','Rivian','Chevrolet','Other']}/>{input('model','Model', 'text',true)}{input('trim','Trim / edition')}{input('zip','Service ZIP code','text',true)}</div><div className="quiet-note"><Shield size={18}/><span>Every vehicle is different. We’ll confirm preparation and any repairs after an inspection.</span></div></>}
 {step===1&&<div className="service-list">{services.map(s=>{const Icon=icons[s.icon];const checked=!!selected[s.id];const [film='ceramic',coverage='sides-rear']=(selected.tint||'ceramic:sides-rear').split(':');return <div className={'service-card '+(checked?'chosen':'')} key={s.id}><label className="service-choice"><Icon size={24}/><span><strong>{s.name}</strong><small>{s.description}</small></span><Checkbox aria-label={s.name} checked={checked} onCheckedChange={v=>setSelected(old=>{const n={...old};if(v)n[s.id]=s.id==='tint'?'ceramic:sides-rear':s.options[0][0];else delete n[s.id];return n;})}/></label>{checked&&s.id==='tint'&&<div className="service-option tint-options"><div className="tint-picks"><Pick label="Tint type" value={film} onChange={v=>setSelected(old=>({...old,tint:`${v}:${coverage}`}))} options={tintFilms.map(v=>v[0])} labels={tintFilms.map(v=>v[1])}/><Pick label="Windows to tint" value={coverage} onChange={v=>setSelected(old=>({...old,tint:`${film}:${v}`}))} options={tintCoverage.map(v=>v[0])} labels={tintCoverage.map(v=>v[1])}/></div><div className="tint-guide" aria-label="Tint type comparison"><div><strong>Dyed</strong><span>Lowest price</span><small>Less heat rejection and shorter life.</small></div><div><strong>Carbon</strong><span>Balanced</span><small>Good heat control without metallic signal interference.</small></div><div><strong>Ceramic</strong><span>Best performance</span><small>Top heat and UV rejection; highest price.</small></div></div>{coverage==='specific'&&<p className="fine">Tell us which windows in “special requests” on the next step. We’ll confirm pricing after review.</p>}</div>}{checked&&s.id!=='tint'&&<div className="service-option"><Pick label="Coverage / package" value={selected[s.id]} onChange={v=>setSelected(old=>({...old,[s.id]:v}))} options={s.options.map(p=>p[0])} labels={s.options.map(p=>p[1])}/></div>}</div>})}</div>}
 {step===2&&<><fieldset><legend>When are you hoping to have this done?</legend><RadioGroup value={form.timing} onValueChange={v=>change('timing',v)} className="timing-grid">{timings.map((t,i)=><label className={'timing '+(form.timing===t?'chosen':'')} key={t}><RadioGroupItem value={t} id={'time-'+i}/><span>{t}</span></label>)}</RadioGroup></fieldset>{form.timing==='By a specific date'&&input('deadline','Preferred completion date','date',true)}{(form.timing==='As soon as possible'||form.timing==='By a specific date')&&<div className="warning"><Clock size={18}/><span>Priority request. Expedited work may involve a substantial additional charge. Availability, deadline and any fee must be confirmed by your concierge.</span></div>}<div className="fields"><Pick label="Service preference" value={form.mode} onChange={v=>change('mode',v)} options={modes}/>{(form.mode==='Pickup & return'||selected.transport)&&<Pick label="Transport preference" value={form.transportMethod} onChange={v=>change('transportMethod',v)} options={['Discuss with concierge','Insured driver / valet','Flatbed','Enclosed transport']}/>}</div>{selected.transport&&input('destination','Destination city or ZIP')}<p className="fine">Mobile eligibility and transport pricing are confirmed during follow-up. No appointment is being reserved.</p><label className="field"><span>Vehicle condition or special requests <small>Optional</small></span><textarea value={form.condition} maxLength={2000} onChange={ev=>change('condition',ev.target.value)} placeholder="Existing scratches, dings, old film, an upcoming event…"/></label></>}
 {error&&!modal&&<p role="alert" className="error">{error}</p>}<div className="step-actions">{step>0?<button className="text-button" onClick={()=>setStep(s=>s-1)}><ArrowLeft size={16}/> Back</button>:<span className="fine">No obligation. No payment.</span>}<button className="primary" onClick={step===2?discuss:next}>{step===2?'Discuss My Estimate':'Continue'}<ArrowRight size={17}/></button></div></div></section>
 <aside className="estimate-panel"><div className="vehicle-photo"><img src="/vehicle.jpg" alt="Graphite Porsche 911 parked with a mountain backdrop"/><div className="photo-shade"/><p>FOR THE DRIVE.<br/><span>And everything after.</span></p></div><div className="summary"><p className="eyebrow">YOUR PRELIMINARY ESTIMATE</p><h3>{form.make?[form.year,form.make].join(' '):'Something worth caring for.'}</h3><p className="muted">{form.model||'Your vehicle and services, brought together.'}</p><div className="line-items">{e.lines.length?e.lines.map(l=><div key={l.id}><span>{l.name}<small>{l.package}</small></span><strong>{l.low?money(l.low)+(l.high&&l.high!==l.low?'–'+money(l.high):'+'):'Discuss'}</strong></div>):<p className="empty-estimate">Choose your services to see an initial price guide.</p>}</div>{e.lines.length>0&&<><div className="total"><span>{e.manual?'Priced services subtotal':'Estimated service range'}</span><strong>{e.low?money(e.low)+(e.high>e.low?' – '+money(e.high):'')+(e.open||selected.ppf==='full'||selected.correction?'+':''):'Let’s discuss'}</strong></div><p className="fine">Local-market guide, not a vehicle-specific quote. Preparation, repairs, tax, transportation and rush fees are excluded. Final pricing requires inspection and approval.</p>{selected.ceramic&&selected.correction&&<p className="fine">Correction may overlap with coating preparation. Your concierge will remove any duplicate work from the final quote.</p>}</>}<div className="summary-footer"><Phone size={17}/><span>A conversation, not a commitment.</span></div></div></aside></div>
 <div className="after-estimate"><span className="eyebrow">WHAT HAPPENS NEXT</span><div><b>01</b><span>We talk through your request.</span></div><div><b>02</b><span>We assess your vehicle.</span></div><div><b>03</b><span>You approve the final quote.</span></div></div>
 <section className="standards" aria-labelledby="standards-title"><div className="standards-intro"><p className="eyebrow">PROFESSIONAL STANDARDS</p><h2 id="standards-title">Credentials we recognize and verify</h2><p>Depending on the service, we look for established industry and manufacturer credentials such as these.</p></div><div className="credential-logos"><a href="https://www.3m.com/3M/en_US/graphics-signage-us/resources/installer-training-testing/preferred-graphics-testing-dates/" target="_blank" rel="noreferrer"><span className="logo-frame"><img src="https://www.3m.com/wps/wcm/connect/f1ff6d7b-121e-4024-8f0b-a5111c6c9d3c/preffered_emblem.png?CACHEID=ROOTWORKSPACE-f1ff6d7b-121e-4024-8f0b-a5111c6c9d3c-oNs7fXF&MOD=AJPERES" alt="3M Preferred Installer emblem" loading="lazy"/></span><strong>3M Preferred Installer</strong><small>PPF and automotive film</small></a><a href="https://the-ida.com/" target="_blank" rel="noreferrer"><span className="logo-frame"><img src="https://www.professionaldetailingproducts.com/cdn/shop/files/IDA-Badge_2x_10bf274f-816b-490b-bbbd-ff42b7fadf2e.jpg?v=1729238517&width=1500" alt="International Detailing Association Certified Detailer badge" loading="lazy"/></span><strong>IDA Certified Detailer</strong><small>Professional detailing</small></a><a href="https://iwfa.com/accreditation-testing/" target="_blank" rel="noreferrer"><span className="logo-frame"><img src="https://graphics.averydennison.com/content/grs-responsive/na/en/home/graphics-products/window-films/automotive-window-films/_jcr_content/center_parsys/manual_1320679000/parsys_main/column_control/item1/parsys_column/image.img.png/1677254677078.png" alt="International Window Film Association logo" loading="lazy"/></span><strong>IWFA Accreditation</strong><small>Automotive window film</small></a><a href="https://www.xpel.com/training-certifications" target="_blank" rel="noreferrer"><span className="logo-frame"><img src="https://www.jackcardetailing.co.uk/media/k2/items/cache/a27a3b73d355048c6bab885897085f62_XL.jpg" alt="XPEL Certified Installer badge" loading="lazy"/></span><strong>XPEL Certified Installer</strong><small>Film and coating installation</small></a></div><div className="standards-grid"><article><strong>Wheel-repair capability</strong><span>Documented straightening, refinishing and structural-repair capability, with safety inspection.</span></article><article><strong>USDOT / FMCSA & insurance</strong><span>Required carrier authority and commercial insurance for applicable vehicle transport.</span></article></div><p className="credential-note">Certification marks belong to their respective owners. Credentials vary by specialist and service and are verified before work is confirmed.</p></section>
 <footer><span>CAPITAL AUTO CONCIERGE</span><span>Pricing subject to review</span><a href="/pricing">Estimate methodology</a><a href="/leads">Concierge login</a></footer></main>
 <Dialog open={modal} onOpenChange={v=>{if(!busy)setModal(v);}}><DialogContent className="contact-dialog"><DialogTitle>{success?'Request received.':'Let’s talk about your vehicle.'}</DialogTitle><DialogDescription>{success?'We saved your request. A concierge will contact you shortly; no appointment or charge has been made.':'Tell us how to reach you. This is a request for a conversation, not a booking.'}</DialogDescription>{success?<><div className="success-icon"><Check/></div><p>Reference: {success.slice(0,8).toUpperCase()}</p><p className="fine">We’ll send a confirmation to the email address you provided. Keep the reference number above for your records.</p><button className="primary full" onClick={()=>setModal(false)}>Done <Check size={16}/></button></>:<form onSubmit={submit}><div className="fields">{input('name','Name','text',true)}{input('phone','Phone','tel',true)}{input('email','Email','email',true)}{input('contactTime','Best time to contact you')}</div><input type="text" name="website" tabIndex={-1} autoComplete="off" value={website} onChange={ev=>setWebsite(ev.target.value)} style={{position:'absolute',left:'-9999px',width:1,height:1,opacity:0}} aria-hidden="true"/>{turnstileKey&&<div id="cac-turnstile" style={{margin:'6px 0 14px'}}/>}<label className="consent"><Checkbox checked={consent} onCheckedChange={v=>setConsent(v===true)} aria-label="Contact consent"/><span>I agree to be contacted about this request. This does not sign me up for marketing.</span></label><p className="fine">Your contact details and vehicle request are saved for concierge follow-up. Photos can be requested during that conversation.</p>{error&&<p className="error" role="alert">{error}</p>}<button className="primary full" disabled={busy||!consent}>{busy?'Saving request…':'Request a conversation'}<ArrowRight size={16}/></button></form>}</DialogContent></Dialog>
 </>;
}
